# Codecov configuration
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 15%
        threshold: 5%
        if_ci_failed: error

    patch:
      default:
        target: 15%
        threshold: 10%
        if_ci_failed: error

  range: 10..90
  round: down
  precision: 2

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "src/__tests__/**"
  - "src/__mocks__/**"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/*.d.ts"
  - "esbuild.config.mjs"
  - "jest.config.js"

github_checks:
  annotations: true
